/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e2e2e2",
        "primary-fixed-dim": "#ffb3b4",
        "tertiary-container": "#646565",
        "tertiary-fixed": "#e3e2e2",
        "primary-container": "#c51c39",
        "error-container": "#ffdad6",
        "tertiary": "#4c4d4d",
        "surface-container-low": "#f3f3f3",
        "error": "#ba1a1a",
        "surface-dim": "#dadada",
        "secondary-fixed": "#e5e2e1",
        "on-primary-fixed-variant": "#920023",
        "on-tertiary-container": "#e3e3e3",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-background": "#1a1c1c",
        "tertiary-fixed-dim": "#c6c6c6",
        "inverse-on-surface": "#f1f1f1",
        "inverse-surface": "#2f3131",
        "surface-bright": "#f9f9f9",
        "surface-container-highest": "#e2e2e2",
        "inverse-primary": "#ffb3b4",
        "on-primary-fixed": "#40000a",
        "background": "#f9f9f9",
        "primary-fixed": "#ffdad9",
        "on-tertiary-fixed-variant": "#464747",
        "on-error-container": "#93000a",
        "primary": "#9e0027",
        "secondary-fixed-dim": "#c9c6c5",
        "outline-variant": "#e3bdbd",
        "outline": "#8f6f6f",
        "on-surface": "#1a1c1c",
        "surface": "#f9f9f9",
        "on-primary-container": "#ffdbda",
        "surface-container-high": "#e8e8e8",
        "surface-container": "#eeeeee",
        "secondary-container": "#e5e2e1",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#1c1b1c",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-tint": "#bb1233",
        "secondary": "#5f5e5e",
        "on-surface-variant": "#5b4040",
        "on-secondary-container": "#656464",
        "on-secondary-fixed-variant": "#474646",
        "porsche-silver": "#BEBEBE",
        "jet-black": "#080808",
        "carmine-red": "#C51C39",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "stack-md": "12px",
        "stack-lg": "24px",
        "margin-mobile": "16px",
        "sidebar-width": "280px",
        "margin-desktop": "32px",
        "stack-sm": "4px",
        gutter: "24px",
      },
      fontFamily: {
        "title-lg": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
        "label-lg": ["Inter"],
        "title-md": ["Inter"],
        "label-sm": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
